### ISSUE TITLE
screencast image is badly distorted in gnome/wayland

### ISSUE THREAD

**Issue by titaniumbones** [foss-project/green-recorder#117]
Running under wayland, the screencast quality on my laptop is very poor (see attached image). I think there may be an issue low down in the stack, as I see the same thing when I press Ctrl-Alt-R in Gnome, and also just tried the same thing in Peek.  Any idea what might be causing such an issue? Thanks.
![screenshot from 2019-01-11 09-04-56](https://user-images.githubusercontent.com/364340/51038460-50ad2600-1581-11e9-843d-82d965c56276.png)

**Comment by titaniumbones** [comment]
I found a bug in the gnome-shell issues tracker which suggests this occurs when using any scaling factor other than `1` in the Gnome Control Center. I am able to work around this issue buy resetting the scale to 100%, though unfortunately this makes hte text almost unreadable in my screencasts... Not closing this bug in case you want tto track it, but plese feel free to do so yourself.  
https://gitlab.gnome.org/GNOME/gnome-shell/issues/711

**Comment by mhsabbagh** [comment]
If it was as you described, then this is an upstream bug (there's nothing in my code to fix to change).. Thus, I think it will be fair to keep following it in GNOME bug tracker instead of here.

Thank you for taking time to reporting this and making this software better.

**Comment by titaniumbones** [comment]
just fyi, there seems to be some movement on the upstream bug: https://gitlab.gnome.org/GNOME/gnome-shell/issues/711#note_457044 

I'm not in the habit of pulling gnome-shell from git (!) but if that's something yo udo it might be interesting to see if  green-recorder now works when scaling is applied.

**Comment by BrendanFDMoore** [comment]
I'm experiencing the exact same issue. Landed on Green Recorder after several others (Kazam, Simple) captured nothing but black screen (thanks Wayland).

GR captured garbled video that looks just like the above.

Due to the pixel density of my laptop display (2560x1440 @ 14"), I use 125% scaling factor to get a comfortable font and UI size. 100% is too small and causes eye strain. I can confirm that the scrambling was resolved by switching back to 100% scaling temporarily. 

I had an issue with the captured video not aligning with the selected area in GR (it was tighter). It seems to not want to properly honor the area selection I make.
