### ISSUE TITLE
Cannot select area under Wayland

### ISSUE THREAD

**Issue by snoack** [foss-project/green-recorder#30]
When running Gnome (3.22.2) on Wayland, and choosing "Select an Area" in Green Recorder (2.1.5), and then click "Apply" in the Area Chooser, nothing happens in the user interface, but following is logged to the terminal (I started `green-recorder` from):

```
/bin/sh: 1: aserver: not found
('No alsa found', 127)
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
xwininfo: error: No window with name "Area Chooser" exists!
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 300, in areasettings
    output = subprocess.check_output(["xwininfo -name \"Area Chooser\" | grep -e Width -e Height -e Absolute"], shell=True)[:-1]
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xwininfo -name "Area Chooser" | grep -e Width -e Height -e Absolute']' returned non-zero exit status 1
```

As far as I know, `xwininfo` isn't supposed to work for windows natively handled by Wayland, but only for windows managed by X (or XWayland). In fact, if I run `xwininfo` without options (or `xprop`), I cannot even click on any of Green Recorder's windows.

**Comment by mhsabbagh** [comment]
I can't reproduce your issue here.

We are depending on `GDK_BACKEND=x11` in order to be able to do a lot of things in Green Recorder. This option is set in the .desktop file. So unless you run it after installation from the .desktop file (from applications menu) you won't be able to use the application correctly. Xwininfo would work if you use it with GDK_BACKEND=x11.

**Comment by snoack** [comment]
I see. So the problem is that I started `green-recorder` directly from the command line, rather than through Gnome's UI. How about putting following at the top of the `green-recorder` script, instead of setting environment variable in a `.desktop` file? Then it will work regardless how Green Recorder was started.

```python
import os
os.environ['GDK_BACKEND'] = 'x11'
```

Though, it is not great to have any application rely on X11 under Wayland, in the first place. This only works because there is XWayland (if it is even installed and running), which emulates X11 on top of Wayland.

**Comment by phw** [comment]
> Though, it is not great to have any application rely on X11 under Wayland, in the first place.

See https://github.com/phw/peek#why-no-native-wayland-support for an explanation why the area selection won't work without XWayland for now. That FAQ is for Peek, but the very same applies to the area selection of Green Recorder.

**Comment by samdroid-apps** [comment]
I've got a patch that changes the way area selection works.  Instead of having a window that you drag around, it creates a fullscreen transparent window.  That then includes a rectangle widget, which you can drag around.  Then it works fully on wayland; as the screen coordinates become the window coordinates.

It probably breaks on a multi-moniter system thought.

Patch coming soon :)
