### ISSUE TITLE
How does the new GIF feature work?

### ISSUE THREAD

**Issue by orschiro** [foss-project/green-recorder#49]
Great addition with GIF!

How does it work exactly? I tried the following settings, did the recording, then get the message that it's now being processed but then never get to see a GIF in my destination folder. 

Tested with the latest version on Ubuntu MATE 17.10 Alpha 2.

![image](https://user-images.githubusercontent.com/170947/29012018-60c1710c-7b38-11e7-8caa-98b858313acb.png)

**Comment by mhsabbagh** [comment]
I'd like to refer you to #48, the details are there.

**Comment by orschiro** [comment]
Selecting an area first works, thanks!

I think the app should to force the user to select an area. For example, greying out the record button until the area was selected. What do you think?

**Comment by mhsabbagh** [comment]
Well, for GIF users should select area (even with other apps, using the whole screen and recording it as GIF will give you a huge GIF size and probably it won't work). But since we are providing more than one format to use (MKV, MP4, WEBM, AVI..) users shouldn't be forced to select an area each time.

**Comment by orschiro** [comment]
> Well, for GIF users should select area

Agree...

> (even with other apps, using the whole screen and recording it as GIF will give you a huge GIF size and probably it won't work)

...but do all users know this?
