### ISSUE TITLE
Weird big icon when recording (again)

### ISSUE THREAD

**Issue by orschiro** [foss-project/green-recorder#51]
I remember we had this problem solved in the past...

Tested with latest version of Green Recorder on Ubuntu MATE 17.10 Alpha 2.

![image](https://user-images.githubusercontent.com/170947/29022167-884b5d02-7b68-11e7-8b2c-0cd6d4454aba.png)

**Comment by mhsabbagh** [comment]
Yep. The problem is that my older solution has triggered a bug in GNOME. It makes the icon not visible at all on it. Since I had to choose someone to sacrifiace, I chose MATE since it has less number of users.

This could be solved by simply loading a different icon name (and path) when the interface is MATE. Let me digg into it a big.

**Comment by orschiro** [comment]
> I chose MATE since it has less number of users.

Hmm, I am really wondering what MATE does differently than all the others...

**Comment by mhsabbagh** [comment]
Fixed in 3.0.4

**Comment by orschiro** [comment]
Can confirm the fix, thank you!
